apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dgg04ul31-nodejs 
  janus-idp.io/tekton: dgg04ul31-nodejs
  backstage.io/kubernetes-id: dgg04ul31-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dgg04ul31-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml